name: 'Conventional Release'
description: 'Releases a new version of the project and generate a changelog using the conventional commits standard.'
author: 'Justia Inc.'

runs:
  using: 'node12'
  main: 'node_modules/@justia/releaser/dist/cli/index.js'

branding:
  icon: 'file-minus'
  color: 'blue'

inputs:
  git-message:
    description: 'Commit message to use'
    default: 'chore(release): ${version}'
    required: false

  github-release:
    description: 'Don''t publish a github release if set false. Default: true'
    default: true
    required: false

  release-name:
    description: 'GitHub Release title'
    default: 'Release ${version}'
    required: false

  npm-publish:
    description: 'NPM Publish. Default: false'
    default: false
    required: false

  preset:
    description: 'The preset from Conventional Changelog to use'
    default: 'angular'
    required: false

  versioning-specification:
    description: 'Versioning specification to use. Options: semver, calver'
    default: 'semver'
    required: false

  calver-format:
    description: 'Format of calver. More info: https://www.npmjs.com/package/calver#available-format-tags'
    default: 'YYYY.MM.MICRO'
    required: false

  output-file:
    description: 'File to output the changelog to'
    default: 'CHANGELOG.md'
    required: false

  require-commits:
    description: 'Do nothing when the changelog from the latest release is empty'
    default: true
    required: false

  require-upstream:
    description: 'Requires upstream to push the changelog'
    default: false
    required: false

  git-user-name:
    description: 'The git user.name to use for the commit'
    required: false

  git-user-email:
    description: 'The git user.email to use for the commit'
    required: false

  fallback-version:
    description: 'The fallback version if a previous version doesn''t exists'
    default: '0.0.0'
    required: false

  base-branch:
    description: 'The base branch of repository'
    default: 'master'
    required: false

  head-branch:
    description: 'The head branch of repository'
    default: 'develop'
    required: false

  use-pr:
    description: 'Create a pull request for the change'
    default: true
    required: false

  automerge-pr:
    description: 'Automerge the pull request created'
    default: true
    required: false

  use-version-branch:
    description: 'Use a versioned branch'
    default: true
    required: false

  remove-version-branch:
    description: 'Remove version branch when the pull request is merged'
    default: true
    required: false

outputs:
  changelog:
    description: 'The generated changelog for the new version'
  version:
    description: 'The new version'
  json-result:
    description: 'RAW json result'
  latest-version:
    description: 'The latest version'
